name: pcpn
description: PCPN Commandline server
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  mysql_client: ^0.0.27
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3
  path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.15
