var serverStatus = "offline";
var serverIpAdd = '172.17.254.29';
var serverPort = '80';
var dbLocation = 'C:/pcpn_db';
var errorServer = '';
// var webpageLocation = 'D:/Tibud-Systems/AAATIBUDCARE_(FRONTEND)/pcpn_web_pages/build/web';
var webpageLocation = '//media/sf_shared_2/build/web';
var serverDart;
var terminal_text = '';
var conn;
var masterlist = [];